source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JTNavigationController_Example', :exclusive => true do
  pod 'JTNavigationController', :path => '../'
end

target 'JTNavigationController_Tests', :exclusive => true do
  pod 'JTNavigationController', :path => '../'

  
end
